name: Feature request
description: "Make a suggestion"
labels: ["Type - Request", "Needs - Review"]
body:
  - type: markdown
    attributes:
      value: |
        > [!Important]
        > Check that you're on the [latest version](https://raw.githubusercontent.com/Josh65-2201/Discord-Windows-11-theme/main/Discord_Windows_11.theme.css#:~:text=%40version). Version number is at the top of the file
        > Check for existing issues by searching for key words that you put in your description

  - type: input
    id: version
    attributes:
      label: Theme version
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
    validations:
      required: true